export const HOME_COUCOU_BEGIN = 'HOME_COUCOU_BEGIN';
export const HOME_COUCOU_SUCCESS = 'HOME_COUCOU_SUCCESS';
export const HOME_COUCOU_FAILURE = 'HOME_COUCOU_FAILURE';
export const HOME_COUCOU_DISMISS_ERROR = 'HOME_COUCOU_DISMISS_ERROR';
